apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httptoolkit-website-route
  namespace: httptoolkit-website
spec:
  parentRefs:
    - name: primary-gateway
      namespace: gateway
      sectionName: https-httptoolkit-tech
    - name: secondary-gateway
      namespace: gateway
      sectionName: https-httptoolkit-tech
  hostnames:
    - "httptoolkit.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: httptoolkit-website
          port: 4000