apiVersion: v1
kind: Service
metadata:
  name: httptoolkit-website
  namespace: httptoolkit-website
spec:
  selector:
    app: httptoolkit-website
  ports:
    - name: http-port
      protocol: TCP
      port: 4000
      targetPort: 4000